AWSTemplateFormatVersion: "2010-09-09"
Transform: "AWS::Serverless-2016-10-31"
Description: "SAM template for Serverless framework service: "

Resources:
  ${lambda_name}:
    Type: "AWS::Serverless::Function"
    Properties:
      Handler: ${lambda_handler}
      Runtime: nodejs6.10
      MemorySize: 128
      Timeout: 30
      CodeUri: ./.serverless/${lambda_name}.zip
      Events:
        Event1:
          Type: Schedule
          Properties:
            Schedule: cron(0 10 ? * MON-FRI *)
    Policies:
      - AmazonEC2FullAccess
      - AWSLambdaFullAccess
      - AmazonS3FullAccess
      - CloudWatchFullAccess
      - AmazonSESFullAccess
      - AmazonSNSFullAccess
      - AWSCloudTrailReadOnlyAccess
